### ISSUE TITLE
[bug] MANIFEST.MF is missing content

### ISSUE THREAD

**Issue by Mcayear** [quentin452/The-Lord-of-the-Rings#32]
## Detailed Explanation

from lastest `lotrmod.jar`:
![image](https://github.com/user-attachments/assets/1a7549f8-01f2-49b8-916a-486969d73667)

current content:
```yml
Manifest-Version: 1.0

```

correct content:
```yml
Manifest-Version: 1.0
FMLCorePluginContainsFMLMod: true
FMLCorePlugin: lotr.common.coremod.LOTRLoadingPlugin

```

Obviously, it lacks `FMLCorePluginContainsFMLMod` and `FMLCorePlugin`, which will cause FML to fail to recognize LOTR as a coremod and cause a series of problems, such as enchantment failure.

## fml-client.log
```log
[main/DEBUG] [FML/]: Not found coremod data in LOTRModfork.v36.29.jar
```
